// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/task_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1118755205459423278),
      name: 'TodoEntity',
      lastPropertyId: const IdUid(5, 5834576521784261789),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7525969620255790271),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 493147969398754190),
            name: 'taskTitle',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8929739133152593380),
            name: 'taskDescription',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4216278169317355200),
            name: 'taskDone',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5834576521784261789),
            name: 'creationDate',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 1118755205459423278),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TodoEntity: EntityDefinition<TodoEntity>(
        model: _entities[0],
        toOneRelations: (TodoEntity object) => [],
        toManyRelations: (TodoEntity object) => {},
        getId: (TodoEntity object) => object.id,
        setId: (TodoEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TodoEntity object, fb.Builder fbb) {
          final taskTitleOffset = object.taskTitle == null
              ? null
              : fbb.writeString(object.taskTitle!);
          final taskDescriptionOffset = object.taskDescription == null
              ? null
              : fbb.writeString(object.taskDescription!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, taskTitleOffset);
          fbb.addOffset(2, taskDescriptionOffset);
          fbb.addBool(3, object.taskDone);
          fbb.addInt64(4, object.creationDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final creationDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = TodoEntity(
              taskTitle: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              taskDescription: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              creationDate: creationDateValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(creationDateValue))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..taskDone =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TodoEntity] entity fields to define ObjectBox queries.
class TodoEntity_ {
  /// see [TodoEntity.id]
  static final id =
      QueryIntegerProperty<TodoEntity>(_entities[0].properties[0]);

  /// see [TodoEntity.taskTitle]
  static final taskTitle =
      QueryStringProperty<TodoEntity>(_entities[0].properties[1]);

  /// see [TodoEntity.taskDescription]
  static final taskDescription =
      QueryStringProperty<TodoEntity>(_entities[0].properties[2]);

  /// see [TodoEntity.taskDone]
  static final taskDone =
      QueryBooleanProperty<TodoEntity>(_entities[0].properties[3]);

  /// see [TodoEntity.creationDate]
  static final creationDate =
      QueryIntegerProperty<TodoEntity>(_entities[0].properties[4]);
}
